// @ts-check
/**
 * Native Share Sheet Module
 * Handles native share sheet integration via Capacitor
 */

import { Share } from '@capacitor/share';
// @ts-ignore - Capacitor types are declared globally

export class ShareSheetManager {
  /**
   * Share shopping list
   * @param {Array} shoppingList - Shopping list items
   * @returns {Promise<void>}
   */
  async shareShoppingList(shoppingList: any[]): Promise<void> {
    const text = this.formatShoppingList(shoppingList);

    try {
      await Share.share({
        title: 'Main Shopping List',
        text: text,
        dialogTitle: 'Share Shopping List',
      });
    } catch (error) {
      console.error('[ShareSheet] Failed to share:', error);
      // Fallback to clipboard
      this.copyToClipboard(text);
    }
  }

  /**
   * Share meal plan
   * @param {Object} mealPlan - Meal plan object
   * @returns {Promise<void>}
   */
  async shareMealPlan(mealPlan: any): Promise<void> {
    const text = this.formatMealPlan(mealPlan);

    try {
      await Share.share({
        title: 'Main Meal Plan',
        text: text,
        dialogTitle: 'Share Meal Plan',
      });
    } catch (error) {
      console.error('[ShareSheet] Failed to share:', error);
      this.copyToClipboard(text);
    }
  }

  /**
   * Share recipe
   * @param {Object} recipe - Recipe object
   * @returns {Promise<void>}
   */
  async shareRecipe(recipe: any): Promise<void> {
    const text = this.formatRecipe(recipe);

    try {
      await Share.share({
        title: recipe.name,
        text: text,
        url: recipe.verified_url || recipe.fallback_url,
        dialogTitle: 'Share Recipe',
      });
    } catch (error) {
      console.error('[ShareSheet] Failed to share:', error);
      this.copyToClipboard(text);
    }
  }

  /**
   * Format shopping list for sharing
   * @param {Array} shoppingList - Shopping list items
   * @returns {string} Formatted text
   */
  formatShoppingList(shoppingList: any[]): string {
    const lines = ['🛒 Main Shopping List\n'];

    shoppingList.forEach((item) => {
      const quantity = item.quantity || 1;
      lines.push(`  ${quantity}x ${item.name}`);
    });

    lines.push('\nGenerated by Main');
    return lines.join('\n');
  }

  /**
   * Format meal plan for sharing
   * @param {Object} mealPlan - Meal plan object
   * @returns {string} Formatted text
   */
  formatMealPlan(mealPlan: any): string {
    const lines = ['📅 Main Meal Plan\n'];

    Object.keys(mealPlan)
      .sort()
      .forEach((date) => {
        lines.push(`\n${date}:`);
        mealPlan[date].forEach((meal: any) => {
          lines.push(`  ${meal.mealType}: ${meal.recipeName}`);
        });
      });

    lines.push('\nGenerated by Main');
    return lines.join('\n');
  }

  /**
   * Format recipe for sharing
   * @param {Object} recipe - Recipe object
   * @returns {string} Formatted text
   */
  formatRecipe(recipe: any): string {
    const lines = [
      `🍽️ ${recipe.name}`,
      '',
      `⏱️ ${recipe.time} minutes`,
      `👥 Serves: ${recipe.servings}`,
      `⭐ Rating: ${recipe.rating}/5`,
      '',
      'Ingredients:',
      ...(recipe.ingredients || []).map((i: any) => `  • ${i}`),
      '',
    ];

    if (recipe.verified_url) {
      lines.push(`View full recipe: ${recipe.verified_url}`);
    }

    lines.push('Generated by Main');
    return lines.join('\n');
  }

  /**
   * Copy text to clipboard (fallback)
   * @param {string} text - Text to copy
   */
  async copyToClipboard(text: string): Promise<void> {
    try {
      await navigator.clipboard.writeText(text);
      alert('Copied to clipboard!');
    } catch (error) {
      console.error('[ShareSheet] Failed to copy to clipboard:', error);
      // Fallback: create textarea and select
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      alert('Copied to clipboard!');
    }
  }

  /**
   * Check if share is available
   * @returns {Promise<boolean>}
   */
  async canShare() {
    return (Share as any).canShare();
  }
}

// Global share sheet instance
let globalShareSheet: ShareSheetManager | null = null;

/**
 * Get or create the global share sheet manager
 * @returns {ShareSheetManager}
 */
export function getShareSheet() {
  if (!globalShareSheet) {
    globalShareSheet = new ShareSheetManager();
  }
  return globalShareSheet;
}
